"""Module containing the initial variables"""

# Numbers of players
NB_PLAYERS = 8

# Numbers of rounds
NB_ROUNDS = 4

# Title
TITLE = "Welcome to the chess program !"

# Main menu
MAIN_MENU = "CHESS MAIN MENU\n\n\
PRESS 1 FOR NEW TOURNAMENT\n\n\
PRESS 2 FOR MANAGE PLAYERS\n\n\
PRESS 3 FOR SHOW REPORTS\n\n\
PRESS 0 FOR QUIT"

# Manage players menu
MANAGE_PLAYERS_MENU = "MANAGE PLAYERS MENU\n\n\
PRESS 1 FOR CREATE NEW PLAYER\n\n\
PRESS 2 FOR MANAGE EXISTING PLAYERS\n\n\
PRESS 0 FOR QUIT"

# New player menu
NEW_PLAYER_MENU = "NEW PLAYER MENU\n\n\
PRESS 1 FOR CREATE NEW PLAYER\n\n\
PRESS 0 FOR QUIT"
# New tournament menu
NEW_TOURNAMENT_MENU = "NEW TOURNAMENT MENU\n\n\
PRESS 1 FOR CREATE TOURNAMENT\n\n\
PRESS 0 FOR QUIT"

START_TOURNAMENT_MENU = "START TOURNAMENT\n\n\
PRESS 1 FOR START TOURNAMENT\n\n\
PRESS 0 FOR QUIT"
